spring.application.name=user

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-user
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://mfebohxh:k4MWUeQPfAD_89HDnMMczht0UPEhN1Di@beaver.rmq.cloudamqp.com/mfebohxh
broker.queue.email.name=default.email