spring.application.name=email
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-email
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://mfebohxh:k4MWUeQPfAD_89HDnMMczht0UPEhN1Di@beaver.rmq.cloudamqp.com/mfebohxh

broker.queue.email.name=default.email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ddtests01@gmail.com
spring.mail.password=**** **** **** ****
spring.mail.properties.mail.smtp.outh=true
spring.mail.properties.mail.smtp.starttls.enable=true
